myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('schedule/', views.todo, name='schedule'),
    path('send/', views.send, name='send'),
    path('deleteSchedule/<id>',views.deleteSched, name='deleteSched'),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    matkul = models.CharField(max_length=50)
    todo = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField()
    place = models.CharField(null=True, max_length=100)
    category = models.CharField(null=True, max_length=30)

myapp/views.py
from django.shortcuts import render
from .models import Todo
from .form import Add_ToDoList
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime
from django.shortcuts import get_object_or_404

response = {}
# Create your views here.
def index(request):
    return render(request, 'index.html',)
def about(request):
    return render(request, 'aboutme.html')
def contacts(request):
    return render(request, 'contacts.html')

def todo(request):
    toDoList = Todo.objects.all().values()
    response['toDoList'] = convert_quaryset_into_json(toDoList)
    response['form'] = Add_ToDoList
    return render(request, 'schedule.html', response)

def send(request):
    form = Add_ToDoList(request.POST)

    if request.method == 'POST' and form.is_valid():
        print(request.POST)
        date_converted = datetime.strptime(request.POST['date'], '%Y-%m-%d')
        time_converted = datetime.strptime(request.POST['time'], '%H:%M')
        log = Todo(matkul = request.POST['matkul'], todo = request.POST['todo'], date = date_converted, time = time_converted, place = request.POST['place'], category = request.POST['category'])
        log.save()

    return HttpResponseRedirect('/schedule/')

def convert_quaryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

def deleteSched(request, id=None):
    toDoObject = get_object_or_404(Todo, pk=id)
    toDoObject.delete()
    return HttpResponseRedirect('/schedule/')

myapp/templates/aboutme.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>About Me</title>
    <link rel="icon" href ="{% static '/img/sra02.png' %}" type="image/x-icon">
</head>
<body id="aboutMe">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'myapp:index' %}">
                <img src="{% static '/img/sra02.png' %}" alt="logo web" width="30" height="30"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myapp:about' %}">About Me<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Experiences">Experiences</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Skills">My Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:contacts' %}">Contacts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:schedule' %}">My Schedule</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row aboutAll">
            <div class="col fotow align-items-center">
                <img src="{% static '/img/fotow.png' %}" width="344" height="459">
            </div>
            <div class="col about">
                <b id="aboutTitle">About Me</b><br><br>
                My name is Safira Rizki Anartya. People call me Safira/Ila. I’m 19 years old.
                I'm a university student who loves to learn what I like. I’m currently studying at Universitas Indonesia. 
                I’m an Information System students. There are many things I enjoy, such as Netflix, watch KDramas and eating.
            </div>
        </div>
    </div>
    <div class="gap" id="Experiences">
        <div class="experiences align-items-center">
            <br><br><b id="aboutTitle">Experiences</b><br><br>
            <u>COMPFEST</u><br>
            Staff of Digital Marketing<br><br>
            <u>DPM Fasilkom UI</u><br>
            Staff of Media, Creative, and Design<br><br>
            <u>Wisuda Genap Fasilkom UI 2019</u><br>
            VPIC of Documentation<br><br>
            <u>UI Ethnovaganza</u><br>
            VPIC of Design<br><br>
    </div>
    <div class="gap" id="Skills">
        <div class="skills align-items-center">
            <b id="aboutTitle">My Skills</b><br><br>
            <u>Design</u><br>
            Adobe Illustrator<br>
            Adobe Photoshop<br>
            Figma<br><br>
            <u>Programming</u><br>
            Python<br>
            Java<br>
            HTML5<br>
            CSS3<br><br>
            <u>Language</u><br>
            English<br>
            Korean
    </div>
</body>

</html>

myapp/templates/contacts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Contacts</title>
    <link rel="icon" href ="{% static '/img/sra02.png' %}" type="image/x-icon">

</head>
<body id="contactsNavbar">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'myapp:index' %}">
                <img src="{% static '/img/sra02.png' %}" alt="logo web" width="30" height="30"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:about' %}">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Experiences">Experiences</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Skills">My Skills</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'myapp:contacts' %}">Contacts<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:schedule' %}">My Schedule</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>
<body id="contactsIcon">
    <div class="container">
        <div class="gap flex-column">
            <div class="contact text align-items-center">
                <blockquote style="z-index: 2">
                    <br><br>
                    you can reach me on
                    <br><br>
                    <a href="https://instagram.com/safirarizkia">
                        <img src="{% static '/img/instaicon.png' %}" alt="instagram icon" width="91px" height="91px">  
                    </a>
                    <a href="https://twitter.com/sapearare">
                        <img src="{% static '/img/twittericon.png' %}" alt="twitter icon" width="91px" height="91px">    
                    </a>
                    <a href="http://line.me/ti/p/~sfrrzkanrty">
                        <img src="{% static '/img/lineicon.png' %}" alt="line icon" width="91px" height="91px">    
                    </a>
                    <a href="mailto:safirarizkia85@gmail.com">
                        <img src="{% static '/img/mailicon.png' %}" alt="mail icon" width="91px" height="91px">    
                    </a>
                    <br><br>
                </blockquote>
            </div>
        </div> 
    </div>
</body>
</html>

myapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <link rel="icon" href ="{% static '/img/sra02.png' %}" type="image/x-icon">
</head>
<body id="indexBody">
    <div class="container">
        <div class="gap flex-column">
            <div class="landing image align-items-center">
                <blockquote style="z-index: 2">
                    <img src="{% static '/img/sra.png' %}" alt="logo web"width="1000" height="400">
                </blockquote>
            </div>
            <a href="{% url 'myapp:about' %}"><button type="button" class="button1 align-items-center">About Me</button></a>
        </div> 
    </div>
</body>
</html>

myapp/templates/schedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Safira's Schedule</title>
    <link rel="icon" href ="{% static '/img/sra02.png' %}" type="image/x-icon">
</head>
<body>
  <nav class="navbar navbar-expand-lg fixed-top navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'myapp:index' %}">
            <img src="{% static '/img/sra02.png' %}" alt="logo web" width="30" height="30"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myapp:about' %}">About Me</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#Experiences">Experiences</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#Skills">My Skills</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myapp:contacts' %}">Contacts</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'myapp:schedule' %}">My Schedule<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
  </nav>
  <div class="container">
    <h1>Safira's Schedule</h1>
    <div id="text">
      <div class="row mx-lg">
        <div class="col-12 col-md-6">
          <form action="{% url 'myapp:send' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Upload Schedule</button>
          </form>
        </div>
        <div class="col-12 col-md-6">
          <table class="table table-borderless">
            <thead>
              <tr>
                <th scope="col">Mata Kuliah/Events</th>
                <th scope="col">To-Do</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Place</th>
                <th scope="col">Category</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for todolists in toDoList %}
                <td class="matkul">{{ todolists.matkul }}</td>
                <td class="todo">{{ todolists.todo }}</td>
                <td class="date">{{ todolists.date }}</td>
                <td class="time">{{ todolists.time }}</td>
                <td class="place">{{ todolists.place }}</td>
                <td class="category">{{ todolists.category }}</td>
                <td>
                  <form action="{% url 'myapp:deleteSched' todolists.id %}" method="GET">
                    <button type="submit" class="btn btn-primary">Delete</button>
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</body>
</html>